apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-api-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kancharlav/argocd-app.git
    targetRevision: HEAD
    path: deployment2
  destination:
    server: https://kubernetes.default.svc
    namespace: app2-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
