apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-api-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-api-1
  template:
    metadata:
      labels:
        app: hello-world-api-1
    spec:
      containers:
        - name: api
          image: nmatsui/hello-world-api
          ports:
            - containerPort: 80
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
