apiVersion: v1
kind: Service
metadata:
  name: hello-world-api-1
spec:
  selector:
    app: hello-world-api-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort